name: Run CLI unit tests and lint

on:
  pull_request:
    branches: 
      - "main"
    paths: 
      - "cli/**"
  push:
    branches: 
      - "main"
    paths: 
      - "cli/**"

defaults:
  run:
    working-directory: ./cli

jobs:
  cli-tests:
    name: Run unit tests and lint
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: v20
      - run: ls -al
      - run: npm ci
      - run: npm run test
      - run: npm run lint 