name: CVE Scanning for Maven

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8,18 * * 1-5'
  push:
    paths:
      - '**/pom.xml'
      - '.github/workflows/maven-cve-ignore-list.xml'
      - '.github/workflows/cve-scanning-node.yml'

jobs:
  depchecktest:
    runs-on: ubuntu-latest
    name: depecheck_test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn install
        working-directory: maven
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@1b5d19fd4a32ff0ff982e8c9d8e27dbf7ac8a46c
        id: Depcheck
        env:
          JAVA_HOME: /opt/jdk
        with:
          project: 'translator'
          path: 'translator'
          format: 'HTML'
          out: 'reports' # this is the default, no need to specify unless you wish to override it
          args: >
            --suppression ./maven/allow-list.xml
            --failOnCVSS 5
            --enableRetired

      - name: Upload Test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: Depcheck report
          path: ${{ github.workspace }}/reports