name: CVE Scanning for Node.js

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8,18 * * 1-5'
  push:
    paths:
      - '**/package.json'
      - '**/package-lock.json'
      - '.github/workflows/node-cve-ignore-list.xml'
      - '.github/workflows/cve-scanning-node.yml'

jobs:
  node-modules-scan:
    name: ${{ matrix.module-folder }}-node-scan
    runs-on: ubuntu-latest
    continue-on-error: false
    strategy:
      matrix:
        module-folder: [
          'cli',
          'docs',
          'visualizer' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Build project with NPM
        run: npm install --omit=dev
        working-directory: ${{ matrix.module-folder }}
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@1b5d19fd4a32ff0ff982e8c9d8e27dbf7ac8a46c
        id: Depcheck
        with:
          project: '${{ matrix.module-folder }}'
          path: '${{ matrix.module-folder }}'
          format: 'HTML'
          out: '${{ matrix.module-folder }}-reports'
          args: >
            --suppression .github/node-cve-ignore-list.xml
            --nodeAuditSkipDevDependencies
            --nodePackageSkipDevDependencies
            --failOnCVSS 5
            --enableRetired
      - run: |
          echo `echo UPNAME=${{matrix.module-folder}} | tr '/' '-'` >> $GITHUB_ENV
          shell: bash
      - name: Upload Test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: Depcheck report
          path: ${{ github.workspace }}/${{ matrix.module-folder }}-reports